version: '3.8'

services:
  app:
    image: raviendalpatadu/ci-cd-tutorial-sample-app:latest
    container_name: sample-app-staging
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///app.db
      - DEBUG=False
    volumes:
      - app_data:/sample-app/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  app_data:
