name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to rollback'
        required: true
        type: choice
        options:
        - development
        - staging
      previous_tag:
        description: 'Previous working image tag to rollback to'
        required: true
        default: 'latest'

jobs:
  rollback:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Rollback to previous version
      run: |
        echo "🔄 Rolling back ${{ github.event.inputs.environment }} to tag: ${{ github.event.inputs.previous_tag }}"
        
        # Update the image tag in docker-compose file
        if [ "${{ github.event.inputs.environment }}" = "development" ]; then
          sed -i 's|image: raviendalpatadu/ci-cd-tutorial-sample-app:.*|image: raviendalpatadu/ci-cd-tutorial-sample-app:${{ github.event.inputs.previous_tag }}|' docker-compose.dev.yml
          docker-compose -f docker-compose.dev.yml pull
          docker-compose -f docker-compose.dev.yml down
          docker-compose -f docker-compose.dev.yml up -d
        else
          sed -i 's|image: raviendalpatadu/ci-cd-tutorial-sample-app:.*|image: raviendalpatadu/ci-cd-tutorial-sample-app:${{ github.event.inputs.previous_tag }}|' docker-compose.stage.yml
          docker-compose -f docker-compose.stage.yml pull
          docker-compose -f docker-compose.stage.yml down
          docker-compose -f docker-compose.stage.yml up -d
        fi
        
        echo "✅ Rollback to ${{ github.event.inputs.environment }} completed"

    - name: Health Check After Rollback
      run: |
        echo "🔍 Performing health check after rollback..."
        sleep 30  # Wait for container to start
        
        # Check if the application is responding
        for i in {1..5}; do
          if curl -f http://localhost:8000/ > /dev/null 2>&1; then
            echo "✅ Health check passed after rollback"
            exit 0
          fi
          echo "⏳ Waiting for application to start... (attempt $i/5)"
          sleep 10
        done
        
        echo "❌ Health check failed after rollback"
        docker-compose logs
        exit 1
